src/background/utils/shouldOpenUrlInBrowser.ts
Remove Zoom Oauth links from list of URLs that should open in Electron. This will allow the zoom OAuth flow to take place in the user's browser
=> Allow zoom OAuth url to open in browser

src/background/useWindowService/openLogInWindow/listenForRedirects.ts
We updated Auth0 to use a custom domain, but the Electron app is still listening for redirects to the old Auth0 domain, so the app is no longer redirecting users to their browser for the Google sign in flow.
Add the new custom Auth0 domain to the list of domains that we detect when determining whether a redirect should be opened in the browser. I left the old domain in there for now in case anyone is running old web code.
=> Fix Google browser sign in with Auth0 custom domain

package-lock.json, package.json, src/background/background.ts, src/background/types.ts, src/background/useWindowService/getWindowOpenRequestHandler.ts, src/background/useWindowService/openCreateGoogleMeetWindow/configureCloseHandler.ts, src/background/useWindowService/openCreateGoogleMeetWindow/getCreateGoogleMeetWindowBrowserOptions.ts, src/background/useWindowService/openCreateGoogleMeetWindow/index.ts, src/background/useWindowService/openCreateGoogleMeetWindow/openCreateGoogleMeetWindow.ts, src/background/useWindowService/openCreateGoogleMeetWindow/scrapeAndSaveMeetingUrl.ts, src/background/useWindowService/openCreateGoogleMeetWindow/types.ts, src/background/useWindowService/useWindowService.ts, src/background/utils/index.ts, src/background/utils/parseQueryParams.ts, src/preload.ts
Currently, Swivvel only supports teams that use Zoom. However, many teams use Google Meet instead.
Support a workflow where users can click a button in the web app to open a new Google Meet meeting.
=> Support Google Meet MVP

src/background/useWindowService/openCreateGoogleMeetWindow/scrapeAndSaveMeetingUrl.ts
In commit ba8a01ee632a0d36f3fa117ead43b1ca7a98ebdc, we added support for opening a new Google Meet breakout room. This works by opening `https://meet.google.com/getalink` in an Electron window and automatically clicking the "Join" button.
When testing on production, one user received the following prompt before the `/getalink` page opened:
Since our desktop app couldn't find a "Join" button after 10 seconds, it gave up trying. Eventually the user confirmed their identity and got to the `/getalink` page, but by that point we were no longer looking for the "Join" button.
Don't give up on trying to find and click the "Join" button until the Electron window is closed.
=> Support Google Meet breakouts when asked for identity verification

src/background/utils/shouldOpenUrlInBrowser.ts
Allow slack OAuth links to open in the browser rather than electron
=> Send slack oauth flow through browser

src/background/background.ts, src/background/handlePowerMonitorStateChanges.ts, src/background/pollForIdleTime.ts, src/background/useWindowService/types.ts, src/background/useWindowService/useWindowService.ts, src/background/useWindowService/utils/closeBrowserWindow.ts, src/background/useWindowService/utils/index.ts
Closing the windows on sleep and re-opening them on resume solves (or attempts to solve) a handful of issues:
1. We have observed (in a very small subset of users) the app getting into a weird state when a Mac comes out of sleep mode. Opening the developer tools shows blank Elements and Console tabs, and clicking the "Join" button shows the spinner but hangs.
2. We have received various error alerts at late times of the night that seem to indicate that the app is unable to fetch data from our back end. Our assumption is that the computer is asleep and this is causing some kind of connectivity problem.
3. For many users, their computer sleeps overnight. Closing and re-opening the windows can make sure that the client has the latest version of the web app code when the user resumes their …
=> Close windows on sleep; re-open on wake

src/background/handlePowerMonitorStateChanges.ts
In commit e08c30a4a2d50ef604d2845288fae7e2405cf276, we made it so all of the Electron windows close when a user's computer goes to sleep and then re-open when the computer wakes.
There were many reasons for this (see the commit description), but one was that the app would get in a bad state when users started their day after keeping the app open all night. We assumed this was because the computer was going to sleep, but after releasing this fix some users were still getting into the bad state in the morning. It turns out that these users were locking their screens, not sleeping their computer.
Update the window close/re-open logic to run both on sleep/wake _and_ lock/unlock.
=> Close windows on lock; re-open on unlock

src/background/useWindowService/openTransparentWindow/openTransparentWindow.ts, src/background/utils/loadUrl.ts
In commit 77b5b8801796eba17334edf70e267935c459c267, we implemented logic to close all of the Electron windows when the computer is locked and re-open them when the computer is unlocked. However, sometimes on unlock (or resume) users get the following error:
and then the Swivvel app closes.
Best guess is that the network connection is inactive and the transparent window fails to open.
There could be any number of reasons that the transparent window fails to load, many of them just temporary issues. To solve the issue above, as well as any other temporary failure, this commit introduces a retry mechanism when loading the transparent window page.
=> Retry loading of notifications URL into transparent window

src/background/background.ts, src/background/configureIpcHandlers.ts, src/background/pollForIdleTime.ts, src/preload.ts
The transparent window is responsible for sending idle change events to the server. However, sometimes the transparent window isn't available or is unable to contact the server. This is currently causing us to drop idle status change events, resulting in users appearing to be idle when they are not.
To avoid losing idle change events, we now put them all in a buffer and continually attempt to send that buffer to the transparent window. After the transparent window successfully syncs an event, it informs the Electron app, which then removes the event from the buffer.
=> Buffer idle status change events

build/entitlements.mac.plist, package.json, src/background/useWindowService/openGoogleMeetWindow/openGoogleMeetWindow.ts
Video for Google Meets is not working on the Mac. It is working for me when I build locally. I think this is because I did not include video in the app's entitlement list.
=> Add video to mac entitlements list

src/background/getDeepLinkHandler.ts, src/background/pollForIdleTime.ts, src/background/useWindowService/openGoogleMeetWindow/loadMeetingUrl.ts, src/background/useWindowService/openGoogleMeetWindow/openGoogleMeetWindow.ts, src/background/useWindowService/openHqWindow/configureAppActivateHandler.ts, src/background/useWindowService/openHqWindow/getHqWindowBrowserOptions.ts, src/background/useWindowService/openHqWindow/openHqWindow.ts, src/background/useWindowService/openHqWindow/types.ts, src/background/useWindowService/openHqWindow/updateTray.ts, src/background/useWindowService/openLogInWindow/openLogInWindow.ts, src/background/useWindowService/openSettingsPageInHqWindow.ts, src/background/useWindowService/openSetupWindow/openSetupWindow.ts, src/background/useWindowService/openTransparentWindow/configureCloseHandler.ts, src/background/useWindowService/openTransparentWindow/openTransparentWindow.ts, src/background/useWindowService/openTransparentWindow/pollForMouseEvents.ts, src/background/useWindowService/useWindowService.ts, src/background/utils/loadUrl.ts
Whenever a window fails to load a URL, we currently show an error message and quit the entire app. We implemented it this way because this was the easiest way make sure that the app didn't end up in a broken state that the user couldn't recover from.
However, we have now encountered a number of situations where quitting the app is particularly disruptive and confusing to users. For example, now that we destroy all windows when a user locks their screen, it is common for the HQ window to fail to load the URL on unlock because the internet connection hasn't been established yet. In this situation, the user currently sees a scary error message and the app quits.
Add a new `onError` option to the `loadUrl()` function that allows us to decide exactly how we want errors to be handled for each …
=> Handle URL load errors more gracefully; improve logging

src/background/useWindowService/openHqWindow/getHqWindowBrowserOptions.ts, src/background/useWindowService/openTransparentWindow/getTransparentBrowserWindowOptions.ts, src/background/useWindowService/openTransparentWindow/openTransparentWindow.ts, src/background/useWindowService/openTransparentWindow/resizeOnDisplayChange.ts, src/background/useWindowService/openTransparentWindow/utils/index.ts, src/background/utils/getFullscreenBounds.ts, src/background/utils/index.ts
When the HQ window is opened, we want to position it to take up the full screen so that users can see as much of the page as possible. We're currently doing that by setting the size & position to be the same as the `workArea` value that we get from the Electron `screen` module.
However, the `workArea` value is sometimes incorrect. On Ubuntu 23.04, this caused the title bar of the HQ window to be transparent when it opened, presumably because we were settings the window to be larger than the available screen area. We previously worked around this by setting `frame: false` for Linux, but that made it impossible to drag the window around or close/minimize it using the window title bar buttons.
In commit b6b6d4f941a9fa82098b884e83fd90af54716249, we created a `getBounds()` function for the …
=> Reuse fullscreen bounds logic for HQ window positioning

.github/pull_request_template.md, .github/workflows/check-pr.yml, src/background/useWindowService/openTransparentWindow/openTransparentWindow.ts
The Swivvel audio room widget is always on top of all windows and can be minimized but not closed completely. This makes it hard to take screenshots without the widget in them.
Use the `window.setContentProtection(true)` command to prevent the transparent window from appearing in screenshots. According to the [Electron docs](https://www.electronjs.org/docs/latest/api/browser-window#winsetcontentprotectionenable-macos-windows):
> Prevents the window contents from being captured by other apps.
>
> On macOS it sets the NSWindow's sharingType to NSWindowSharingNone. On Windows it calls SetWindowDisplayAffinity with WDA_EXCLUDEFROMCAPTURE. For Windows 10 version 2004 and up the window will be removed from capture entirely, older Windows versions behave as if WDA_MONITOR is applied capturing a …
=> Hide transparent window in screenshots

package.json, src/background/utils/quitApp.ts
Auto-updating was not working on windows. When the update was run, it would uninstall the previous version of the app without replacing it. We could tell this because `C:\Users\ericropiak\AppData\Local\Programs\swivvel\` was empty after the "update" command was run.
Cedric stumbled across this PR, which suggested that the artifact name has to be different from the product name. https://github.com/electron-userland/electron-builder/issues/7184
Update them import of auto updater in one file to match the imports elsewhere. This ensures the same instance is being used across our entire app
Tested in a windows VM. Verified that running subsequent installs would first uninstall the previous version and then install the new version, without breaking any desktop shortcuts
=> Fix auto updating on windows

src/background/useWindowService/openTransparentWindow/openTransparentWindow.ts
In commit 08a3070ffd4ad143cb823e56fef749a3d89e3f29, we made a change to stop the transparent window from getting focus when it opens. This broke the always-on-top behavior on Linux.
Call `window.setAlwaysOnTop(true)` after showing the transparent window to make sure that it is properly configured to be always on top.
=> Fix bug where transparent window not always on top on Linux

src/background/handlePowerMonitorStateChanges.ts
Brian ran into [This Bug](https://swivvel.slack.com/archives/C041MFH7VMF/p1697127153690059), which came from the recent change in `handlePowerMonitorStateChanges` - Where I set it up to close the windows after 10 minutes. 
But if the window closed and we still had the timeout, the `transparentWindow` never opened. Causing a state where we can't get that open again
Always open the windows even if there is a `timeout`. Since if the window already exists it will use that one
Add extra logging with more information so we can properly debug this if another error occurs.
=> Fix `powerMonitor` timeout bugs and add extra logs

package-lock.json, package.json, src/background/background.ts, src/background/configureApp.ts, src/background/configureIpcHandlers.ts, src/background/configureSentry.ts, src/background/setUserDataPath.ts, src/background/useTrayService/utils/getBaseMenuItems.ts, src/background/useWindowService/openTransparentWindow/getLogger.ts, src/background/useWindowService/openTransparentWindow/openTransparentWindow.ts, src/preload.ts
We don't have a lot of visibility into errors that users encounter in the Electron app. Right now our debugging process requires us to ask the user to explain the issue and manually send us the console logs and the Electron log file. This makes it difficult to debug issues.
Add automatic Sentry error reporting, as well as a new "Send Bug Report" item in the tray menu that will attach the Electron `main.log` file with the Sentry alert.
Change `npm run dev` to `electron .` because the development environment wasn't detecting our `package.json` so it was using the app name `Electron` instead of `Swivvel`. This was causing log files to be written to an `Electron-development/` directory.
=> Report errors to Sentry; add manual error reporting tray item

src/background/pollForIdleTime.ts
In commit 8bd2bf8890b06995ec449ee8a7d2fe4b673195a0, we attempted to fix a bug in the idle poller where we could end up writing a log line every second for hours. When someone locks their screen or suspends their computer, we close the transparent window. If there is an idle change event in the buffer, it'll be stuck there until the transparent window opens again. Sometimes the computer isn't unlocked/resumed for hours, causing us to write a log line every second for a very long time, polluting the log.
However, even after that commit there was still a log line in the idle poller that was getting written every second.
Stop logging how many events are in the buffer unless the transparent window is available to receive those events.
=> Stop writing idle poller log line every second

package-lock.json, package.json, src/background/useTrayService/utils/getBaseMenuItems.ts
In commit 571dd85205a99f3f03eff18b8eec872463b9cf47, we added the ability for users to easily send us their log files by clicking a "Send Bug Report" menu item in the tray menu. This triggers a Sentry alert with the title "Manual bug report" and attaches the log files.
However, we realized that Sentry ends up grouping these alerts, so it would be very easy to accidentally miss one.
Use a unique fingerprint for the manual bug report Sentry alert so that it never gets grouped.
I also added the user's email address and current time to the alert message so we have a little more context when looking at a list of manual bug report Sentry alerts.
=> Use unique fingerprint for manual bug report Sentry alerts

src/background/configureIpcHandlers.ts, src/background/useWindowService/openTransparentWindow/configureMousePassThroughHandler.ts, src/background/useWindowService/openTransparentWindow/openTransparentWindow.ts, src/background/useWindowService/openTransparentWindow/pollForMouseEvents.ts, src/background/utils/index.ts, src/background/utils/isMac.ts, src/preload.ts
Users were reporting that they tried to take a screenshot of a window on Mac and the screenshot ended up being a blank screen with the widget in it.
In commit a375ef619c69497c43557c6a61ca2428d37de8a6, we attempted to fix this by calling `window.setContentProtection(true)` on the transparent window. This is supposed to prevent apps from taking screenshots of the transparent window.
However, after releasing that change, users got a new issue when trying to take screenshots. Instead of being a blank page, they would get an error.
It turns out that this error only happens when using the "Capture Selected Window" screenshot option. This option allows you to select a specific window for the screenshot. But when users tried this, they could only select the transparent window, not any windows …
=> Use `mousemove` to detect when mouse over transparent area

src/background/background.ts, src/background/setUserDataPath.ts, src/background/useWindowService/openTransparentWindow/getLogger.ts
In commit 571dd85205a99f3f03eff18b8eec872463b9cf47, we made two changes related to logging:
1. We started writing logs from the transparent window into a file.
2. We fixed a bug where app data was stored in a directory called "Electron" instead of "Swivvel-development". Fixing this bug required us to explicitly configure the development logs to be written into the new "Swivvel-development" directory.
Both of these changes configured the log path using code like this:
```ts
path.join(app.getPath(`userData`), `logs`, `${name}.log`);
```
This worked on Windows and Linux because the log data is stored in a `logs/` sub-directory inside of the Electron user data directory.
However, on Mac the log files are _not_ stored in the user data directory. The user data is stored in …
=> Write transparent window logs & dev logs to correct directory

src/background/handlePowerMonitorStateChanges.ts, src/background/useWindowService/utils/openBrowserWindow.ts
When a user locks or sleeps their computer, we close all windows after 10 minutes. If they unlock or resume their computer within 10 minutes, we call `windowService.openTransparentWindow()`.
In this scenario, the transparent window already exists, so we end up just calling `window.show()`. This results in the transparent window getting focus. We don't want the transparent window to get focus when it doesn't need to because it can cause weird corner case bugs, e.g. with screenshots.
Use `showInactive()` to prevent an existing transparent window from getting focus when opened.
Minor refactoring of `handlePowerMonitorStateChanges.ts` to remove code duplication.
=> Open transparent window without focus on unlock/resume

src/background/configureAutoUpdates/configureAutoUpdates.ts, src/background/configureAutoUpdates/pollForUpdates.ts, src/background/pollForIdleTime.ts
There are two events that can cause a lot of spam in our logs:
1. When there are idle events buffered but they can't be handled by the transparent window (such as when the user is not logged in)
2. When the auto-updater checks for updates
Remove the log line that says when we are sending idle events to the transparent window. It's not ideal to lose this visibility, but the cleaner log is likely more important than having this log line. Also, we still write a log line every time a new event is added to the buffer, and whenever an event is successfully handled by the transparent window, so we aren't losing visibility completely.
For the auto-updater log lines, we made two changes:
- Only poll for updates every 10 minutes instead of every minute. We don't realistically need to be polling …
=> Reduce log spam; check for updates every 10 minutes

.eslintrc.js, .github/workflows/build.yml, package.json, signWindows.js
If we don't sign our windows code, the user will have to jump through a bunch of hoops when they download the app. Plus our product seems very illegitimate:
https://github.com/swivvel/swivvel-electron/assets/131678810/ec7d4a2b-bec4-451f-a3fd-ad7fb241e3a6
We should sign our windows app. We do this, we purchased a Code Signing Certificate form Digicert. Due to [new regulations](https://knowledge.digicert.com/generalinformation/new-private-key-storage-requirement-for-standard-code-signing-certificates-november-2022.html), signing keys need to be stored on certain hardware. In order for us to satisfy that requirement, our key will be hosted by Digicert in our [Digicert One Keylocker](https://one.digicert.com/).
As a part of our build process, we can use a secret API to access our certificate …
=> Add code signing for Windows

signWindows.js
Noticed when running a test build for windows that the local build was failing because it didnt have the  necessary code signing setup. This skips the code signing bit if the prereqs arent in place
=> Allow building windows code locally without signing

src/background/background.ts, src/background/configureMousePassThroughHandler.ts, src/background/useWindowService/openTransparentWindow/configureMousePassThroughHandler.ts, src/background/useWindowService/openTransparentWindow/openTransparentWindow.ts
In commit 01aaef242b92feb25853d16e87ec424f4ae22d44, we updated our transparent window mouse pass-through strategy for Macs to use a `mousemove` handler. However, we forgot to check whether the transparent window has been destroyed before calling `transparentWindow.setIgnoreMouseEvents()`, so now some users are getting the [following error](https://swivvel.sentry.io/issues/4554113703/?project=4504796469657600&query=is%3Aunresolved&referrer=issue-stream&stream_index=0):
> TypeError: Object has been destroyed
Unregister the `mousemove` handler when the transparent window is destroyed.
=> Unregister mousemove when transparent window destroyed

src/background/background.ts, src/background/configureIpcHandlers.ts, src/background/types.ts, src/background/useWindowService/openGoogleMeetWindow/openGoogleMeetWindow.ts, src/background/useWindowService/openGoogleMeetWindow/patchGetDisplayMediaOnUrlChange/patchGetDisplayMedia/patchGetDisplayMedia.ts, src/background/useWindowService/openGoogleMeetWindow/patchLoginFlow/addBannerToLoginFlow/addBannerToLoginFlow.ts, src/background/useWindowService/openGoogleMeetWindow/patchLoginFlow/addBannerToLoginFlow/index.ts, src/background/useWindowService/openGoogleMeetWindow/patchLoginFlow/addBannerToLoginFlow/insertBanner.ts, src/background/useWindowService/openGoogleMeetWindow/patchLoginFlow/clickSignInIfInLobby.ts, src/background/useWindowService/openGoogleMeetWindow/patchLoginFlow/index.ts, src/background/useWindowService/openGoogleMeetWindow/patchLoginFlow/patchLoginFlow.ts, src/background/useWindowService/openGoogleMeetWindow/patchLoginFlow/prefillEmailAndAdvance.ts, src/background/useWindowService/utils/index.ts, src/background/useWindowService/utils/loadRawJsFromFile.ts
The first time that a user opens a google meet, they will be prompted to log in because we dont have their google session in electron. This could be confusing, especially if the user does not know that they need to sign in.
Three big pieces we can automate here:
1) If a user is in the waiting room for a meeting and they aren't signed in, we can auto-click the sign in button for them
2) We can add a banner to the sign in flow explaining why they need to connect
3) We can auto-populate the email address and advance to the next step for the user
If breakout room doesnt yet exist...
https://github.com/swivvel/swivvel-electron/assets/131678810/94d6252e-3812-4a0d-8f53-7ce75abe3550
If breakout room already exists....
https://github.com/swivvel/swivvel-electron/assets/131678810/5afab23d-a96d-4d65- …
=> Improve login flow in Google meet window

src/background/configureIpcHandlers.ts, src/background/useTrayService/utils/getBaseMenuItems.ts, src/background/utils/triggerSentryError.ts
We can now trigger an error on behalf of a user, but we need a way to differentiate those from manually reported errors.
Make the error message configurable
=> Update message for users triggered for users

src/background/useWindowService/openGoogleMeetWindow/patchGetDisplayMediaOnUrlChange/patchGetDisplayMedia/patchGetDisplayMedia.ts, src/background/useWindowService/openGoogleMeetWindow/patchLoginFlow/patchLoginFlow.ts
We got a Sentry error where we tried to execute some javascript inside the google meet window, but the window had been destroyed.
We should check that the window is still hanging around before trying to execute anything in it
=> Check meet window hasnt been destroyed before executing js

src/background/background.ts, src/background/configureAutoUpdates/configureAutoUpdates.ts, src/background/configureAutoUpdates/pollForUpdates.ts
We have been getting a ton of Sentry alerts from calls to `autoUpdater.checkForUpdatesAndNotify()` that are all related to the user having network connectivity problems. There is nothing we can do about these issues, so the alerts are currently causing a lot of alerting noise.
Catch and ignore errors thrown by calls to `autoUpdater.checkForUpdatesAndNotify()`.
Since we run `checkForUpdatesAndNotify` synchronously when the app starts up, I also moved our `configureAutoUpdates()` function in `background.ts` to be called at the very end so that it won't block any other setup if it happens to take a while to execute the function.
I also opted to increase the length of time between checks for new versions from 10 minutes to 30 minutes. This was a somewhat arbitrary change not prompted by …
=> Ignore auto-update errors; increase update poll to 30 minutes

src/background/utils/getFullscreenBounds.ts, src/background/utils/getUbuntuVersion.ts, src/background/utils/index.ts, src/background/utils/isUbuntuVersionGreaterOrEqual.ts
In Ubuntu 23.10, the OS top bar changed from 27px tall to 32px tall. This caused the audio room widget to be slightly misplaced when aligned to the bottom of the screen because we had to manually adjust the transparent window bounds to account for the OS top bar because the working area size was being incorrectly reported to Electron.
Update the transparent window bounds calculation to support newer versions of Ubuntu with a 32px tall OS top bar.
=> Fix transparent window bounds on Ubuntu >= 23.10

src/background/useWindowService/openGoogleMeetWindow/patchGetDisplayMediaOnUrlChange/patchGetDisplayMediaOnUrlChange.ts
We received a `TypeError: Object has been destroyed` Sentry alert in the `patchGetDisplayMediaOnUrlChange()` function.
Don't call `window.webContents.on('did-finish-load', ...)` if the window has been destroyed.
=> Check if window destroyed in patchGetDisplayMediaOnUrlChange

src/background/useTrayService/utils/getBaseMenuItems.ts
We have been getting some bug reports that have been very difficult to reproduce. Ideally we would get on a screen share with the user, but we would need access to the dev tools on the transparent window for the screen share to be effective. On Windows and Linux there is no easy way to open the transparent window dev tools. Also, sometimes the issue we're trying to debug involves the audio room widget disappearing completely, making it difficult to open dev tools on Mac as well.
Always show the Dev Tools tray menu option.
=> Always show Dev Tools tray menu option

src/background/useWindowService/utils/openBrowserWindow.ts, src/preload.ts
We have an Ubuntu 23.04 user who is opening Swivvel in the desktop app, but the app thinks that it is not running in the desktop app because `window.electron` is undefined. So one of the following must be happening
- The preload script is failing to get included in the browser window options (perhaps there is an issue with the path)
- The preload script is getting included but is not running
- The preload script is running but `contextBridge.exposeInMainWorld()` is not working
Add logs so we can verify the path of the preload script and make sure that it is successfully running.
=> Add logs to debug issue where `window.electron` is undefined

.eslintrc.js, package-lock.json, package.json, src/background/useWindowService/openTransparentWindow/getFileLogger.ts
Newer versions of packages are available.
Upgrade to newest versions:
```
@sentry/electron                   😍  UPDATE!   Your local install is out of date. https://github.com/getsentry/sentry-electron#readme
npm install @sentry/electron@4.14.0 --save to go from 4.13.0 to 4.14.0
electron-log                       😎  MAJOR UP  Major update available. https://github.com/megahertz/electron-log#readme
npm install electron-log@5.0.0 --save to go from 4.4.8 to 5.0.0
electron-serve                     😍  UPDATE!   Your local install is out of date. https://github.com/sindresorhus/electron-serve#readme
npm install electron-serve@1.2.0 --save to go from 1.1.0 to 1.2.0
@types/uuid                        😍  UPDATE!   Your local install is out of date. …
```
=> Upgrade all packages to newest versions

src/background/background.ts, src/background/configureGlobalKeyboardShortcuts.ts, src/background/setUserDataPath.ts, src/preload.ts
When someone starts talking to you in Swivvel, it can be annoying to try to get to the widget and click unmute, especially if the widget is currently collapsed.
Register `Alt+Shift+U` as a keyboard shortcut for muting and unmuting.
I tried this keyboard shortcut on Linux, Mac and Windows and it does not seem to be registered on any of them (though individual apps and websites might use it).
In commit 5efb90a1263c70cd34312be338f377fc44ca42d0 we upgraded the `electron-log` package. One of the changes was to deprecate the `resolvePath` field on the file transport and rename it to `resolvePathFn`. There is still one place we are using the old `resolvePath` name, so I updated it to be `resolvePathFn`.
=> Add keyboard shortcut for toggling mute state

src/background/useWindowService/openGoogleMeetWindow/configureCloseHandler.ts, src/background/useWindowService/openGoogleMeetWindow/openGoogleMeetWindow.ts, src/background/useWindowService/openGoogleMeetWindow/pollForJoinAndLeaveEvents/triggerMeetingLeftEvent.ts, src/background/useWindowService/openGoogleMeetWindow/triggerMeetingCreatedEvent.ts
We received a couple `TypeError: Object has been destroyed` error alerts in the code that manages the Google Meet window.
Check if the Google Meet window is destroyed before calling any functions on the window object.
=> Check if Google Meet window destroyed in more places

src/background/useWindowService/openGoogleMeetWindow/openGoogleMeetWindow.ts
To use Google Meet in Swivvel, users need to sign in to Google workspace. Some companies will use okta to sign in. As a part of the okta sign in flow, the user is redirected to a url on the `google.com` domain. Because that domain has not been safelisted, electron kicked it out to the browser which prevents the sign in flow from completing
Allow the url to open in the electron window
=> Allow link to google in meet window for Okta sign in

src/background/utils/getFullscreenBounds.ts
A user mentioned that the audio room sidebar widget was extending off the bottom of their screen. They have the following displays:
| Display | Work Area |
|-|-|
| 0 | `{x: 0, y: 0, width: 1600, height: 900}` |
| 1 | `{x: 1600, y: 27, width: 1920, height: 1053}` |
We positioned the transparent window to:
```
{x: 0, y: 27, width: 1920, height: 1053}
```
The primary display is Display 1. Notice how `height`, `width` and `y` were correctly set to the work area position, but `x` was set to 0. The system should be positioning the transparent window to:
```
{x: 1600, y: 27, width: 1920, height: 1053}
```
Use the work area `x` position when positioning the transparent window.
=> Position transparent window using work area `x`

src/background/useWindowService/getWindowOpenRequestHandler.ts, src/background/useWindowService/useWindowService.ts
We wanted to show the private beta `HomeScreen` page, but we stopped showing the HQ for logging in.
Handle being passed in a `show` prop to open the HQ window when a user is signed in but has no company
=> Update `onHqRequested` to use `show` param

src/background/configureTransparentWindowResizeHandler.ts, src/background/utils/getFullscreenBounds.ts
In commit b96ce9d2ab90521a5b8b79321339e62be9e7d77f, we updated the positioning strategy for the transparent window on Linux. Instead of relying on the work area bounds (which is unreliable), we now create a temporary invisible window, maximize it, and then read the bounds.
However, there are now a few issues when the transparent window is resized due to a display change (e.g. plugging in an external monitor):
1. Sometimes the temporary window doesn't get closed so it just hangs around
2. Maximizing the temporary window takes a few seconds, during which time the widget might be floating in the middle of the screen
3. In some cases the widget is rendered off screen after a display change. This seems to happen when the resolution width goes down.
A couple small tweaks address the issues …
=> Fix transparent window resize on display change on Linux

src/background/useWindowService/openTransparentWindow/openTransparentWindow.ts
We didn't show the swivvel widget (the transparent window) in screenshots. But this was more of a negative then a positive. 
> some people are trying to share screenshots with colleagues, and we’re hurting their ability to brag about Swivvel.
Delete the code snippet that removed the widget from screenshots
A known bug occurred when screen-shotting the window. I wanted to make sure it didn't get reverted. But when screen-shotting the whole window it works as expected. Outcome:
Other screenshot taken for test:
=> Show the `TransparentWindow` in screenshots

src/background/configureAutoUpdates/pollForUpdates.ts, src/background/configureSentry.ts
In commit b081f9a0d05b6284fd7a69be3978f0b341ec93af, we attempted to stop sending auto-update errors to Sentry because they are too noisy and are almost never actionable. To do so, we wrapped the call to `autoUpdater.checkForUpdatesAndNotify()` in a try/catch. However, this didn't work.
I wrapped `autoUpdater.checkForUpdatesAndNotify()` in a try/catch and added a console log immediately before and after:
```ts
console.log(`+++++++++++++++++++++++++++++++++++++++++ BEFORE`);
try {
await autoUpdater.checkForUpdates();
} catch (err) {
//
}
console.log(`+++++++++++++++++++++++++++++++++++++++++ AFTER`);
```
I then ran the app in a state where the download would fail. I received the following output:
```
+++++++++++++++++++++++++++++++++++++++++ BEFORE
14:47:27.219 › Checking for update …
```
=> Stop sending auto-update errors to Sentry

src/background/useWindowService/openTransparentWindow/openTransparentWindow.ts
In commit 7906dc07df272e71ebf24f57b0668eace47bdfe0, we removed the following setting on the transparent window:
```ts
window.setContentProtection(true);
```
The intention was to make it so that users could take screenshots of the widget when filing bug reports.
However, there was an unintended consequence. Windows users started reporting a blue bar at the top of their screen:
I have no clue why this blue bar appears when content protection is off, but I'm turning content protection back on for now to fix the bug, and then we can take some time to figure out why the blue bar is appearing.
=> Re-enable content protection to prevent blue bar on windows

src/background/useTrayService/utils/getBaseMenuItems.ts
We frequently have to tell users to upgrade the desktop app. Every running version of the app will upgrade automatically at midnight, but sometimes we need users to upgrade before then, such as when we pushed a bug fix.
Right now, the only way to ensure that a user is on the latest version is to tell them to restart the app twice (once to download the update, a second time to install it). This is somewhat awkward.
Add a "Check for Updates" option to the tray menu that checks for a new update and prompts the user to download it if one is available.
=> Add "Upgrade" option to tray menu

src/background/useWindowService/openTransparentWindow/openTransparentWindow.ts
In commit 7906dc07df272e71ebf24f57b0668eace47bdfe0, we removed the following setting on the transparent window:
```ts
window.setContentProtection(true);
```
The intention was to make it so that users could take screenshots of the widget when filing bug reports.
However, there was an unintended consequence. Windows users started reporting a blue bar at the top of their screen:
In commit 52fd914e863dca61b02429d49eb0f306a3c2fe97, we re-enabled content protection to quickly fix the bug and remove the blue bar. However, this is only a bug on Windows, so we don't need to enable content protection on other operating systems.
Only enable content protection if the app is running on Windows.
Ideally we would find a way to disable content protection on Windows, but I found an open GitHub issue about …
=> Allow screenshots of transparent window on Mac

src/background/background.ts, src/background/logSystemInfo.ts
Some users have mentioned that the app is causing their computer to run slowly. It would be handy to have an easy way to get information about each user's OS and hardware to help identify a possible pattern and try to reproduce the issue.
Log some information about the user's system when the app starts.
=> Log OS and hardware specs when app starts

src/background/utils/getFullscreenBounds.ts
In commit b96ce9d2ab90521a5b8b79321339e62be9e7d77f, we updated the positioning strategy for the transparent window on Linux. Instead of relying on the work area bounds (which is unreliable), we now create a temporary invisible window, maximize it, and then read the bounds.
However, when the temporary transparent window is created, it automatically gets focus. This steals focus away from whatever other window the user had open, which is somewhat annoying.
Prevent the temporary transparent window from stealing focus by opening it hidden and then using `showInactive()` to show it without grabbing focus.
=> Prevent temp transparent window from stealing focus

src/background/configureGlobalKeyboardShortcuts.ts
Now that we reference the global shortcut in the mute icons tooltip, there are two places to update if we ever change the tooltip.
Leave a comment reminder so if we do change it the developer will now know to update there as well.
=> Add a comment about referencing the global shortcut

package.json
Some users have been prompted to install Rosetta in order to run Swivvel on Mac. Rosetta allows ARM Macs to run software built for Intel Macs. We should be able to support both.
Add a flag to output universal Mac builds.
=> Create universal Mac builds

src/background/utils/loadUrl.ts
Sometimes the google meet window will close unexpectadly and throw a error, but we have no insight to the actual error being thrown.
Add `err` to the catch logs in `loadUrl.ts`
=> Add `err` log for `loadUrl`

src/background/background.ts, src/background/getDeepLinkHandler.ts, src/background/listenForDeepLinks.ts
We are building a feature that posts a Slack message when a new Swivvel session is started. This message will have a link to join the Swivvel session. This requires a deep link in to the Electron app that runs the code to join the audio room for a specific pod.
Add a new `/join-audio-room-for-pod?podId=xxx` deep link that sends the existing `joinAudioRoomForPod` event to the transparent window.
This commit also fixes a bug where we were slicing the last character off of the deep link when we should not have been.
=> Add deep link handler to join audio room for pod
